language: node_js
cache:
  directories:
    - ~/.npm
    - yarn
notifications:
  email: false
node_js:
  - '10'
env:
  - CI=true
git:
  depth: 5
script:
  - yarn test:cover
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
