language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
git:
  depth: 5
notifications:
  email: false
script:
  - yarn test:cover
  - yarn build
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
